# Journaling Topic Prompt

matches:
  - trigger: ":prompt"
    replace: "{{prompt}}"
    vars:
      - name: prompt
        type: random
        params:
          choices:
            - "When was the last time you tried something new?"
            - "Who do you sometimes compare yourself to?"
            - "What's the most sensible thing you've ever heard someone say?"
            - "What gets you excited about life?"
            - "What life lesson did you learn the hard way?"
            - "What do you wish you spent more time doing five years ago?"
            - "What am I avoiding right now, and why?"
            - "What small thing brought me peace today?"
            - "What do I need to let go of?"
            - "What am I learning about myself this season?"
            - "Where am I making life harder than it needs to be?"
            - "What is one thing you can commit to today, so that your near or distant future self will thank you for?"
            - "What do you hope to reinforce through this journaling practice? It could be as simple as creating a new helpful routine, or as deep as doing inner work and learning more about yourself."
            - "What are you excited about right now or of late? It could be an upcoming holiday, or simply taking some downtime at the end of a long day."
            - "What is your favourite quote, and how does it inspire or comfort you?"
            - "What are you able and willing to let go of this week? It can be a small thing, such as not tidying the entire house due to chronic pain, or a big thing, such as forgiving someone who has done you wrong."
            - "When do you feel most energised? Perhaps a certain time or day, in solitude, or in company? How can you use that energy for yourself and the greater good?"
            - "Do you have a dream that is achievable yet unfulfilled? Dream about it a little more today! And if you have the right energy, perhaps write a few actionable steps that you can do to achieve this."
            - "What do you value most in life? Are you standing by these values and how so? If you aren t, how can you realign yourself with them?"
            - "List three things you can do this year to take better care of your physical health. They can be small things, such as doing a few morning stretches, or a bigger thing such as eating healthier dinners."
            - "List three things you can do this year to take better care of your mental health. It can be as small as saying a positive affirmation every morning, or something a bit bigger such as going to see a psychologist for any mental health issues."
            - "List three things you can do this year to take better care of your emotional well-being. It can be a small thing such as creating a peaceful night routine, or something that you find harder, such as setting personal boundaries."
            - "What would you do if you had an extra hour every day, and why?"
            - "What skill(s) would you most like to learn or build upon and what does that mean to you?"
            - "In expansion of yesterday s journaling prompt, how could you learn or build those skills?"
            - "What was your biggest mistake in life, and what did you learn? How can this lesson help you in future?"
            - "What will you do today that will benefit you tomorrow? If you re journaling at night, then the day after!"
            - "What s something you will regret not doing? Will you do it eventually, and how will you get there?"
            - "Bad moods happen. When you feel like you re in one of those moods, how can you turn things around?"
            - "What is your dream destination and why? Who would you like to accompany you on that trip?"
            - "What is something you would attempt to do, if your health and circumstances permitted you to?"
            - "What was your big win for the day? It could be seemingly simple yet hard, such as getting out of bed whilst in pain. Or something big, such as speaking at a public conference!"
            - "How do you respond to crises or emergencies? How can you improve on that?"
            - "Think about a controversial issue or opinion that you feel strongly about. Now write something defending the opposite. How did that make you feel and did you learn anything about yourself or others?"
            - "What kind of an adult did you want to become as a child? Are you that person now or better? If you re not where you want to be, what steps can you take to work towards it?"
            - "What was your dream job as a child and why? Are you working in that line of work now, and is it everything you thought it would be?"
            - "Describe yourself in 10 words. Do you like what you see? If you don t, why and how can you change that for the better?"
            - "What s your deepest secret desire? What stops you from revealing it to others?"
            - "What helps you stay focused when you feel your mind wandering off?"
            - "What is something in your life that you don t do enough of, but think you should?"
            - "Success is not necessarily related to career or finances. What does success mean to you? How can you have a healthier perspective of success?"

