# Journaling Topic Prompt

matches:
  - trigger: ":prompt"
    replace: "{{prompt}}"
    vars:
      - name: prompt
        type: random
        params:
          choices:
            - "When was the last time you tried something new?"
            - "Who do you sometimes compare yourself to?"
            - "What's the most sensible thing you've ever heard someone say?"
            - "What gets you excited about life?"
            - "What life lesson did you learn the hard way?"
            - "What do you wish you spent more time doing five years ago?"
